src/lexer.rs

This PR is a part of #17, but does not contain all of it.

add single character delimiters

---

src/lexer.rs

#17 
- implemented double character delimiters
- added a test helper `test_kinds` which we can use to test a source against a vec of kinds
- added `next_char` method which move remaining characters by one

Implement two characters delimiters

---

src/lexer.rs
src/snapshots/enderpy__lexer__tests__snapshot_test_lexer-33.snap
src/snapshots/enderpy__lexer__tests__snapshot_test_lexer-34.snap
src/snapshots/enderpy__lexer__tests__snapshot_test_lexer-35.snap
src/snapshots/enderpy__lexer__tests__snapshot_test_lexer-36.snap

Resolves #17
I think all delimiters are now scanned.

Scan three characters delimiters

---

src/lexer.rs
src/snapshots/enderpy__lexer__tests__snapshot_test_lexer-34.snap
src/snapshots/enderpy__lexer__tests__snapshot_test_lexer-35.snap
src/snapshots/enderpy__lexer__tests__snapshot_test_lexer-37.snap
src/snapshots/enderpy__lexer__tests__snapshot_test_lexer-38.snap
src/snapshots/enderpy__lexer__tests__snapshot_test_lexer-39.snap
src/snapshots/enderpy__lexer__tests__snapshot_test_lexer-40.snap
src/snapshots/enderpy__lexer__tests__snapshot_test_lexer-41.snap
src/snapshots/enderpy__lexer__tests__snapshot_test_lexer-42.snap
src/snapshots/enderpy__lexer__tests__snapshot_test_lexer-43.snap
src/snapshots/enderpy__lexer__tests__snapshot_test_lexer-44.snap
src/snapshots/enderpy__lexer__tests__snapshot_test_lexer-45.snap
src/snapshots/enderpy__lexer__tests__snapshot_test_lexer-46.snap
src/snapshots/enderpy__lexer__tests__snapshot_test_lexer-47.snap
src/snapshots/enderpy__lexer__tests__snapshot_test_lexer-48.snap
src/snapshots/enderpy__lexer__tests__snapshot_test_lexer-49.snap
src/snapshots/enderpy__lexer__tests__snapshot_test_lexer-50.snap
src/snapshots/enderpy__lexer__tests__snapshot_test_lexer-51.snap
src/snapshots/enderpy__lexer__tests__snapshot_test_lexer-52.snap
src/snapshots/enderpy__lexer__tests__snapshot_test_lexer-53.snap
src/snapshots/enderpy__lexer__tests__snapshot_test_lexer-54.snap
src/snapshots/enderpy__lexer__tests__snapshot_test_lexer-55.snap
src/snapshots/enderpy__lexer__tests__snapshot_test_lexer-56.snap
src/snapshots/enderpy__lexer__tests__snapshot_test_lexer-57.snap
src/snapshots/enderpy__lexer__tests__snapshot_test_lexer-58.snap
src/snapshots/enderpy__lexer__tests__snapshot_test_lexer-59.snap
src/snapshots/enderpy__lexer__tests__snapshot_test_lexer-60.snap
src/snapshots/enderpy__lexer__tests__snapshot_test_lexer-61.snap

Scan operators

---

src/lexer.rs
src/snapshots/enderpy__lexer__tests__snapshot_test_lexer-62.snap
src/snapshots/enderpy__lexer__tests__snapshot_test_lexer-63.snap
src/snapshots/enderpy__lexer__tests__snapshot_test_lexer-64.snap
src/snapshots/enderpy__lexer__tests__snapshot_test_lexer-65.snap

Add keywords

---

src/lexer.rs
src/snapshots/enderpy__lexer__tests__snapshot_test_lexer-112.snap
src/snapshots/enderpy__lexer__tests__snapshot_test_lexer-113.snap
src/snapshots/enderpy__lexer__tests__snapshot_test_lexer-114.snap

Merge #29 before this!
Closes: #15

Add number literals

---

src/parser/ast.rs
src/parser/parser.rs
src/parser/snapshots/enderpy__parser__parser__tests__yield_expression-2.snap
src/parser/snapshots/enderpy__parser__parser__tests__yield_expression-3.snap
src/parser/snapshots/enderpy__parser__parser__tests__yield_expression.snap

parser: yield

---

src/parser/ast.rs
src/parser/expression.rs
src/parser/parser.rs
src/parser/snapshots/enderpy__parser__parser__tests__await_expression.snap

parser: await

---

src/parser/ast.rs
src/parser/expression.rs
src/parser/parser.rs
src/parser/snapshots/enderpy__parser__parser__tests__expressions_list.snap
src/parser/snapshots/enderpy__parser__parser__tests__starred.snap

parser: expression lists

---

src/parser/ast.rs
src/parser/expression.rs
src/parser/operator.rs
src/parser/parser.rs
src/parser/snapshots/enderpy__parser__parser__tests__named_expression.snap
src/parser/snapshots/enderpy__parser__parser__tests__parse_bool_op-4.snap
src/parser/snapshots/enderpy__parser__parser__tests__parse_subscript-2.snap
src/parser/snapshots/enderpy__parser__parser__tests__parse_subscript-3.snap
src/parser/snapshots/enderpy__parser__parser__tests__parse_subscript-4.snap
src/parser/snapshots/enderpy__parser__parser__tests__parse_subscript.snap
src/parser/snapshots/enderpy__parser__parser__tests__set.snap
src/parser/snapshots/enderpy__parser__parser__tests__subscript-2.snap
src/parser/snapshots/enderpy__parser__parser__tests__subscript-3.snap
src/parser/snapshots/enderpy__parser__parser__tests__subscript-4.snap
src/parser/snapshots/enderpy__parser__parser__tests__subscript-5.snap
src/parser/snapshots/enderpy__parser__parser__tests__subscript-6.snap
src/parser/snapshots/enderpy__parser__parser__tests__subscript-7.snap
src/parser/snapshots/enderpy__parser__parser__tests__subscript.snap
src/parser/snapshots/enderpy__parser__parser__tests__tuple.snap

I opened a portal to hell and daemons wrote this code.

parser: support subscription

---

src/parser/ast.rs
src/parser/parser.rs
src/parser/snapshots/enderpy__parser__parser__tests__parse_call-2.snap
src/parser/snapshots/enderpy__parser__parser__tests__parse_call-3.snap
src/parser/snapshots/enderpy__parser__parser__tests__parse_call-4.snap
src/parser/snapshots/enderpy__parser__parser__tests__parse_call-5.snap
src/parser/snapshots/enderpy__parser__parser__tests__parse_call-6.snap
src/parser/snapshots/enderpy__parser__parser__tests__parse_call-7.snap
src/parser/snapshots/enderpy__parser__parser__tests__parse_call.snap

parser: support call expression

---

src/lexer/lexer.rs
src/lexer/snapshots/enderpy__lexer__lexer__tests__newline-in-nested-structure-0.snap
src/lexer/snapshots/enderpy__lexer__lexer__tests__string-literals-0.snap
src/parser/parser.rs
src/parser/snapshots/enderpy__parser__parser__tests__dict-2.snap
src/parser/snapshots/enderpy__parser__parser__tests__dict-3.snap
src/parser/snapshots/enderpy__parser__parser__tests__dict-4.snap
src/parser/snapshots/enderpy__parser__parser__tests__dict-5.snap
src/parser/snapshots/enderpy__parser__parser__tests__list-2.snap
src/parser/snapshots/enderpy__parser__parser__tests__list-3.snap
src/parser/snapshots/enderpy__parser__parser__tests__list-4.snap
src/parser/snapshots/enderpy__parser__parser__tests__list-5.snap
src/parser/snapshots/enderpy__parser__parser__tests__set-2.snap
src/parser/snapshots/enderpy__parser__parser__tests__set-3.snap
src/parser/snapshots/enderpy__parser__parser__tests__set-4.snap
src/parser/snapshots/enderpy__parser__parser__tests__set-5.snap
src/parser/snapshots/enderpy__parser__parser__tests__tuple-2.snap
src/parser/snapshots/enderpy__parser__parser__tests__tuple-3.snap
src/parser/snapshots/enderpy__parser__parser__tests__tuple-4.snap
src/parser/snapshots/enderpy__parser__parser__tests__tuple-5.snap
src/parser/snapshots/enderpy__parser__parser__tests__tuple.snap
src/parser/string.rs

implicit line joining

---

src/lexer/lexer.rs
src/parser/parser.rs
src/parser/snapshots/enderpy__parser__parser__tests__dict-6.snap
src/parser/snapshots/enderpy__parser__parser__tests__lambda-9.snap
src/parser/snapshots/enderpy__parser__parser__tests__list-6.snap
src/parser/snapshots/enderpy__parser__parser__tests__parse_call-8.snap
src/parser/snapshots/enderpy__parser__parser__tests__parse_name-13.snap
src/parser/snapshots/enderpy__parser__parser__tests__parse_name-14.snap
src/parser/snapshots/enderpy__parser__parser__tests__set-6.snap
src/parser/snapshots/enderpy__parser__parser__tests__subscript-8.snap
src/parser/snapshots/enderpy__parser__parser__tests__tuple-5.snap
src/parser/snapshots/enderpy__parser__parser__tests__tuple-6.snap

parser: allow trailing comma

---

src/lexer/diagnostics.rs
src/lexer/fstring.rs
src/lexer/lexer.rs
src/lexer/mod.rs
src/lexer/snapshots/enderpy__lexer__lexer__tests__f-string-literals-0.snap
src/lexer/snapshots/enderpy__lexer__lexer__tests__f-string-literals-1.snap
src/lexer/snapshots/enderpy__lexer__lexer__tests__f-string-literals-2.snap
src/lexer/snapshots/enderpy__lexer__lexer__tests__f-string-literals-3.snap
src/lexer/snapshots/enderpy__lexer__lexer__tests__f-string-literals-4.snap
src/lexer/snapshots/enderpy__lexer__lexer__tests__f-string-literals-5.snap
src/lexer/snapshots/enderpy__lexer__lexer__tests__f-string-literals-6.snap
src/lexer/snapshots/enderpy__lexer__lexer__tests__raw-f-string-literals-0.snap
src/parser/expression.rs
src/parser/string.rs
src/token.rs

Please red the following section:
https://peps.python.org/pep-0701/#new-tokens

lexer: add fstring tokens pep 701

---

src/lexer/lexer.rs
src/lexer/snapshots/enderpy__lexer__lexer__tests__f-string-literals-7.snap
src/lexer/snapshots/enderpy__lexer__lexer__tests__f-string-literals-8.snap
src/lexer/snapshots/enderpy__lexer__lexer__tests__raw-f-string-literals-1.snap
src/lexer/snapshots/enderpy__lexer__lexer__tests__raw-f-string-literals-2.snap
src/lexer/snapshots/enderpy__lexer__lexer__tests__raw-f-string-literals-3.snap
src/lexer/snapshots/enderpy__lexer__lexer__tests__raw-f-string-literals-4.snap
src/lexer/snapshots/enderpy__lexer__lexer__tests__raw-f-string-literals-5.snap
src/lexer/snapshots/enderpy__lexer__lexer__tests__raw-f-string-literals-6.snap

peps.python.org/pep-0701/#new-tokens

lexer: add scape bracket pattern to fstring

---

src/parser/ast.rs
src/parser/parser.rs
src/parser/snapshots/enderpy__parser__parser__tests__parse_del_stmt-2.snap
src/parser/snapshots/enderpy__parser__parser__tests__parse_del_stmt-3.snap
src/parser/snapshots/enderpy__parser__parser__tests__parse_del_stmt.snap
src/parser/snapshots/enderpy__parser__parser__tests__pass_stmt-2.snap
src/parser/snapshots/enderpy__parser__parser__tests__pass_stmt-3.snap
src/parser/snapshots/enderpy__parser__parser__tests__pass_stmt.snap

parser: add return, del, pass statements

---

parser/src/parser/ast.rs
parser/src/parser/parser.rs
parser/src/parser/snapshots/parser__parser__parser__tests__for_statement-2.snap
parser/src/parser/snapshots/parser__parser__parser__tests__for_statement-3.snap
parser/src/parser/snapshots/parser__parser__parser__tests__for_statement-4.snap
parser/src/parser/snapshots/parser__parser__parser__tests__for_statement.snap
parser/src/parser/snapshots/parser__parser__parser__tests__try_statement-2.snap
parser/src/parser/snapshots/parser__parser__parser__tests__try_statement-3.snap
parser/src/parser/snapshots/parser__parser__parser__tests__try_statement-4.snap
parser/src/parser/snapshots/parser__parser__parser__tests__try_statement-5.snap
parser/src/parser/snapshots/parser__parser__parser__tests__try_statement-6.snap
parser/src/parser/snapshots/parser__parser__parser__tests__try_statement.snap
parser/src/parser/snapshots/parser__parser__parser__tests__while_statement-2.snap
parser/src/parser/snapshots/parser__parser__parser__tests__while_statement-3.snap
parser/src/parser/snapshots/parser__parser__parser__tests__while_statement.snap
parser/src/parser/snapshots/parser__parser__parser__tests__with_statement-2.snap
parser/src/parser/snapshots/parser__parser__parser__tests__with_statement-3.snap
parser/src/parser/snapshots/parser__parser__parser__tests__with_statement-4.snap
parser/src/parser/snapshots/parser__parser__parser__tests__with_statement.snap

Only 2 other statements are left until the parser fully support all python statements 😎 
Closes: #115 
Closes: #118 
Closes: #117 
Closes: #116

parser: for & while statements

---

cli/Cargo.toml
cli/src/cli.rs
cli/src/main.rs

CLI interface

---

cli/Cargo.toml
cli/src/cli.rs
cli/src/main.rs
parser/src/lib.rs
parser/src/parser/mod.rs

CLI dev tools

---

Cargo.toml
cli/src/cli.rs
cli/src/main.rs
parser/src/lib.rs
parser/src/parser/mod.rs
typechecker/Cargo.toml
typechecker/src/build.rs
typechecker/src/build_error.rs
typechecker/src/lib.rs
typechecker/src/nodes.rs
typechecker/src/semantic_analyzer.rs
typechecker/src/settings.rs
typechecker/src/symbol_table.rs

This PR adds basic data structures and interfaces for semantic analyzer and type checker.

typechecker: init

---

parser/src/parser/ast.rs
typechecker/src/build.rs
typechecker/src/semantic_analyzer.rs
typechecker/src/snapshots/typechecker__build__tests__assign_stmt-2.snap
typechecker/src/snapshots/typechecker__build__tests__assign_stmt-3.snap
typechecker/src/snapshots/typechecker__build__tests__assign_stmt-4.snap
typechecker/src/snapshots/typechecker__build__tests__assign_stmt-5.snap
typechecker/src/snapshots/typechecker__build__tests__assign_stmt-6.snap
typechecker/src/snapshots/typechecker__build__tests__assign_stmt.snap
typechecker/src/symbol_table.rs

- New symbol table with local scopes
- Bind function definitions

Refactor symbol table strcture to support nested scopes

---

: Box<EnderpyFile>,
scripts/print_symbol_table.py
test.py
typechecker/src/build.rs
typechecker/src/snapshots/typechecker__build__tests__assign_stmt-2.snap
typechecker/src/snapshots/typechecker__build__tests__assign_stmt-4.snap
typechecker/src/snapshots/typechecker__build__tests__assign_stmt-5.snap
typechecker/src/snapshots/typechecker__build__tests__assign_stmt-6.snap
typechecker/src/snapshots/typechecker__build__tests__assign_stmt.snap
typechecker/src/snapshots/typechecker__build__tests__function_def_symbols.snap
typechecker/src/symbol_table.rs

Add paramter to symbol table nodes

---

parser/src/lexer/lexer.rs
parser/src/lexer/snapshots/enderpy_python_parser__lexer__lexer__tests__ellipsis-0.snap
parser/src/lexer/snapshots/enderpy_python_parser__lexer__lexer__tests__ellipsis-1.snap
parser/src/parser/ast.rs
parser/src/parser/expression.rs
parser/src/parser/parser.rs
parser/src/parser/snapshots/enderpy_python_parser__parser__parser__tests__ellipsis_statement-2.snap
parser/src/parser/snapshots/enderpy_python_parser__parser__parser__tests__ellipsis_statement-3.snap
parser/src/parser/snapshots/enderpy_python_parser__parser__parser__tests__ellipsis_statement-4.snap
parser/src/parser/snapshots/enderpy_python_parser__parser__parser__tests__ellipsis_statement.snap
parser/src/parser/snapshots/enderpy_python_parser__parser__parser__tests__parse_import_statement-10.snap
parser/src/parser/snapshots/enderpy_python_parser__parser__parser__tests__parse_import_statement-11.snap
parser/src/parser/snapshots/enderpy_python_parser__parser__parser__tests__parse_import_statement-12.snap
parser/src/parser/snapshots/enderpy_python_parser__parser__parser__tests__parse_import_statement-13.snap
parser/src/parser/snapshots/enderpy_python_parser__parser__parser__tests__parse_import_statement-14.snap
parser/src/parser/snapshots/enderpy_python_parser__parser__parser__tests__parse_import_statement-15.snap
parser/src/token.rs
typechecker/src/type_check/type_inference.rs

Add ellipsis to parser

---

typechecker/src/semantic_analyzer.rs
typechecker/src/symbol_table.rs
typechecker/test_data/inputs/symbol_table/class_definition.py
typechecker/testdata/output/enderpy_python_type_checker__build__tests__symbol_table@class_definition.py.snap

Add the defined instance attributes in the __init__ method to the symbol table.

Add instance attributes that are defined in the __init__ method

---

typechecker/src/symbol_table.rs
typechecker/src/type_check/test_data/inputs/never.py
typechecker/src/type_check/test_data/output/enderpy_python_type_checker__type_check__type_evaluator__tests__type_evaluator@never.py.snap
typechecker/src/type_check/type_evaluator.rs
typechecker/src/type_check/types.rs

- Add Never type
https://docs.python.org/3/library/typing.html#typing.Never

never type

---

lsp/src/main.rs

Solves first task of this [issue](https://github.com/Glyphack/enderpy/issues/225)

Add Hover capabilities to LPS

---

enderpy/src/main.rs
lsp/src/main.rs
typechecker/src/settings.rs

This fixes #223 and puts the Python executable into the settings struct.

Fixes: Python executable not found

---

parser/src/parser/parser.rs
test.log
typechecker/src/build.rs
typechecker/src/checker.rs
typechecker/src/semantic_analyzer.rs
typechecker/src/symbol_table.rs
typechecker/src/type_evaluator.rs
typechecker/src/types.rs
typechecker/test_data/inputs/import_star_test/a.py
typechecker/test_data/inputs/import_star_test/b.py
typechecker/test_data/output/enderpy_python_type_checker__build__tests__symbols_import_star.snap
typechecker/test_data/output/enderpy_python_type_checker__build__tests__symbols_imports.snap
typechecker/test_data/output/enderpy_python_type_checker__checker__tests__basic_generics.snap
typechecker/test_data/output/enderpy_python_type_checker__checker__tests__basic_types.snap
typechecker/test_data/output/enderpy_python_type_checker__checker__tests__import_star_lookup.snap

- **feat: add import stars to symbol table**
- **fix: import * node span**
- **feat: do symbol lookups on star imported modules**

feat: add import stars to symbol table

---

typechecker/src/checker.rs
typechecker/src/semantic_analyzer.rs
typechecker/src/type_evaluator.rs
typechecker/test_data/inputs/import_star_test/a.py
typechecker/test_data/output/enderpy_python_type_checker__checker__tests__import_star_lookup.snap

Resolving attribute access on modules. Like `os.path` and `os.path.dirname`.

feat: attribute access on imported modules

---

.github/workflows/benchmark.yml
README.md
benchmark/Cargo.toml
benchmark/benches/parser_benchmark.rs
benchmark/benches/typecheck_benchmark.rs
benchmark/test_data/types_very_fast.py
typechecker/src/semantic_analyzer.rs

feat: type checker benchmark

---

README.md

This is pretty basic, but it appears to be working for me.

docs: Basic instructions for getting the LSP running in neovim

---

parser/src/parser/parser.rs
parser/test_data/output/enderpy_python_parser__parser__parser__tests__parse_call-9.snap
typechecker/src/checker.rs
typechecker/src/symbol_table.rs
typechecker/src/type_evaluator.rs
typechecker/test_data/inputs/conformance_tests/annotations_forward_refs.py
typechecker/test_data/output/enderpy_python_type_checker__checker__tests__annotations_forward_refs.snap
typechecker/test_data/output/enderpy_python_type_checker__checker__tests__basic_generics.snap

feat: handle forward references
